import { Component, OnInit } from '@angular/core';
import {Page} from 'tns-core-modules/ui/page'
@Component({
  selector: 'ngb-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent implements OnInit {

  constructor(private page:Page) { }

  ngOnInit() {
    this.page.actionBarHidden=true;
  }

}
