import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { HeaderComponent } from './components/Layout/header/header.component';
import { NativeScriptFormsModule } from 'nativescript-angular/forms';
import {CoreModule} from './core/index';
import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';
import {NativeScriptUIAutoCompleteTextViewModule} from 'nativescript-ui-autocomplete/angular';
import {NativeScriptUISideDrawerModule} from 'nativescript-ui-sidedrawer/angular';
import { HeaderSearchComponent } from './components/Layout/header/components/header-search/header-search-.component';
import { HeaderProfileComponent } from './components/Layout/header/components/header-profile/header-profile.component';
import { HeaderCartComponent } from './components/Layout/header/components/header-cart/header-cart.component';
import { LoginModalNativeComponent } from './components/Auth/login-modal.component.tns';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    HeaderComponent,HeaderSearchComponent,HeaderProfileComponent,HeaderCartComponent,
    LoginModalNativeComponent
  ],
  imports: [
    NativeScriptModule,
    NativeScriptHttpClientModule,
    NativeScriptFormsModule,
    NativeScriptUIAutoCompleteTextViewModule,
    NativeScriptUISideDrawerModule,
    AppRoutingModule,
    CoreModule.forRoot()
  ],
  entryComponents:[LoginModalNativeComponent],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
